<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>25968f4e-d329-4bef-8cdf-8052148122e5</elementGuidId>
    <imagePath></imagePath>
    <name>button_delete3</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.btn-error</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[4]/button[2]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Delete\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-xs btn-error</value>
        <webElementGuid>da08a84f-c2de-4736-b48e-d37484f9ded9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Delete</value>
        <webElementGuid>da08a84f-c2de-4736-b48e-d37484f9ded9</webElementGuid>
    </webElementProperties>
</WebElementEntity>