<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dd28696d-ba52-4dcf-8299-ba407b5858c2</elementGuidId>
    <imagePath></imagePath>
    <name>button_logout</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.btn-ghost</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/aside[1]/button[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Logout\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-ghost text-error mt-10</value>
        <webElementGuid>0665cb54-a385-48f9-a10a-d062b0098e47</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Logout</value>
        <webElementGuid>0665cb54-a385-48f9-a10a-d062b0098e47</webElementGuid>
    </webElementProperties>
</WebElementEntity>