<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8238beea-788b-4a6b-8bec-17df25d5e8dd</elementGuidId>
    <imagePath></imagePath>
    <name>button_reports</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(2) &gt; button</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/aside[1]/ul[1]/li[2]/button[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Reports\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Reports</value>
        <webElementGuid>da08a84f-c2de-4736-b48e-d37484f9ded9</webElementGuid>
    </webElementProperties>
</WebElementEntity>