<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b5e2041f-057f-4820-9ac5-2b73af8792e4</elementGuidId>
    <imagePath></imagePath>
    <name>button_logout2</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.btn</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/aside[1]/button[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Logout\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-ghost text-error mt-10</value>
        <webElementGuid>ed81107c-7b18-4631-a4db-291626665ad7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Logout</value>
        <webElementGuid>ed81107c-7b18-4631-a4db-291626665ad7</webElementGuid>
    </webElementProperties>
</WebElementEntity>