<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>db2002e8-44e8-49a1-bb93-bd3903360c31</elementGuidId>
    <imagePath></imagePath>
    <name>input_jobTitle</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>input:nth-of-type(2)</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/input[2]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>input &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input input-bordered w-full</value>
        <webElementGuid>8d8b1b4b-93ec-4a5c-ae74-b19882ca34be</webElementGuid>
    </webElementProperties>
</WebElementEntity>