<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8cd00fe3-b081-4d79-9912-6e470e1868bf</elementGuidId>
    <imagePath></imagePath>
    <name>button_editDelete</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>${button_editDelete_css_value_1}</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[4]/button[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"${button_editDelete_buttonInternalText_1}\"s &gt;&gt; nth=${button_editDelete_sNth_1}</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-xs btn-info</value>
        <webElementGuid>8d8b1b4b-93ec-4a5c-ae74-b19882ca34be</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Edit</value>
        <webElementGuid>8d8b1b4b-93ec-4a5c-ae74-b19882ca34be</webElementGuid>
    </webElementProperties>
</WebElementEntity>