<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>197bd273-3214-4303-aed8-b8970cc72188</elementGuidId>
    <imagePath></imagePath>
    <name>button_editDelete</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>${button_editDelete_css_value_1}</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[4]/button[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"${button_editDelete_ButtonInternalText_1}\"s &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-xs btn-info</value>
        <webElementGuid>0665cb54-a385-48f9-a10a-d062b0098e47</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Edit</value>
        <webElementGuid>0665cb54-a385-48f9-a10a-d062b0098e47</webElementGuid>
    </webElementProperties>
</WebElementEntity>