<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f97b212b-67f0-42a3-ae70-bd70d82318b3</elementGuidId>
    <imagePath></imagePath>
    <name>button_navigationOptions</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>${button_navigationOptions_css_value_1}</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/aside[1]/ul[1]/li[1]/button[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"${button_navigationOptions_ButtonInternalText_1}\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Reports</value>
        <webElementGuid>ed81107c-7b18-4631-a4db-291626665ad7</webElementGuid>
    </webElementProperties>
</WebElementEntity>