<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ebfbaab7-7899-4f54-83b8-0f57093a498a</elementGuidId>
    <imagePath></imagePath>
    <name>input_name</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>${input_name_css_value_1}</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/input[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>input &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input input-bordered w-full</value>
        <webElementGuid>0665cb54-a385-48f9-a10a-d062b0098e47</webElementGuid>
    </webElementProperties>
</WebElementEntity>