<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>975f6cf1-862d-4688-b652-7839d077efe8</elementGuidId>
    <imagePath></imagePath>
    <name>button_logout</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.flex &gt; button:nth-of-type(2) &gt; [class="h-5\ w-5"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/header[1]/header[1]/div[2]/button[2]/*[name()='svg'][1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Logout\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>h-5 w-5</value>
        <webElementGuid>69de07fb-14b4-49ed-8bbb-36d9a0a47be4</webElementGuid>
    </webElementProperties>
</WebElementEntity>