<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_noManager</name>
   <tag></tag>
   <elementGuidId>42678e54-d4a0-4b71-8615-e0dc24483c01</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/main[1]/section[1]/div[1]/div[1]/div[2]/div[1]/div[6]/div[1]/button[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.transition-colors</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;No Manager&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full flex items-center justify-between px-3 py-2 border rounded-md shadow-sm transition-colors focus:outline-none focus:ring-2 focus:ring-[var(--accent-color)] bg-white border-gray-300 text-gray-900</value>
      <webElementGuid>20d5f32a-4858-4258-a86c-15d6c0292ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No Manager</value>
      <webElementGuid>20d5f32a-4858-4258-a86c-15d6c0292ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20d5f32a-4858-4258-a86c-15d6c0292ca8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
