<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <elementGuidId>7dc4f180-499f-4945-a0ae-e7826e6d5a46</elementGuidId>
   <imagePath></imagePath>
   <name>button_employees</name>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/aside[1]/div[1]/nav[1]/button[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;space-y-2&quot;] > button:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button >> internal:has-text=/^Employees$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <tag></tag>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex w-full items-center gap-3 rounded-lg px-3 py-2 text-left text-sm font-medium transition hover:bg-base-200 text-[var(--accent-color)]</value>
      <webElementGuid>2039e409-0771-4f94-87b2-00623b19f045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employees</value>
      <webElementGuid>2039e409-0771-4f94-87b2-00623b19f045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2039e409-0771-4f94-87b2-00623b19f045</webElementGuid>
   </webElementProperties>
</WebElementEntity>
