<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>26e43fc7-1b81-4f05-8798-5c88e75e08f9</elementGuidId>
    <imagePath></imagePath>
    <name>button_saveEmployee</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ font-semibold\ rounded-lg\ px-4\ py-2\ border-none\ w-full\ sm\:w-auto"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/section[1]/div[1]/div[1]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:has-text=/^Save Employee$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn font-semibold rounded-lg px-4 py-2 border-none w-full sm:w-auto</value>
        <webElementGuid>9a7e84fc-09a0-4c57-b73d-56a8edc349fd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Save Employee</value>
        <webElementGuid>9a7e84fc-09a0-4c57-b73d-56a8edc349fd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>9a7e84fc-09a0-4c57-b73d-56a8edc349fd</webElementGuid>
    </webElementProperties>
</WebElementEntity>