<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f19ecabf-72ac-4730-b272-0b8ad4c59bf3</elementGuidId>
    <imagePath></imagePath>
    <name>span_icon</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="w-5\ h-5"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/section[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]/*[name()='svg'][1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>section button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>w-5 h-5</value>
        <webElementGuid>9a7e84fc-09a0-4c57-b73d-56a8edc349fd</webElementGuid>
    </webElementProperties>
</WebElementEntity>